# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: complex.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='complex.proto',
  package='example.third',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rcomplex.proto\x12\rexample.third\"\'\n\x0b\x43hildObject\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"r\n\rComplexObject\x12\n\n\x02id\x18\x01 \x01(\x05\x12$\n\x05\x62rand\x18\x02 \x01(\x0e\x32\x15.example.third.Brands\x12/\n\x0b\x63hildObject\x18\x03 \x01(\x0b\x32\x1a.example.third.ChildObject*:\n\x06\x42rands\x12\x11\n\rUNKNOWN_BRAND\x10\x00\x12\r\n\tLOW_BRAND\x10\x01\x12\x0e\n\nHIGH_BRAND\x10\x02\x62\x06proto3')
)

_BRANDS = _descriptor.EnumDescriptor(
  name='Brands',
  full_name='example.third.Brands',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_BRAND', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOW_BRAND', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HIGH_BRAND', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=189,
  serialized_end=247,
)
_sym_db.RegisterEnumDescriptor(_BRANDS)

Brands = enum_type_wrapper.EnumTypeWrapper(_BRANDS)
UNKNOWN_BRAND = 0
LOW_BRAND = 1
HIGH_BRAND = 2



_CHILDOBJECT = _descriptor.Descriptor(
  name='ChildObject',
  full_name='example.third.ChildObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='example.third.ChildObject.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='example.third.ChildObject.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=71,
)


_COMPLEXOBJECT = _descriptor.Descriptor(
  name='ComplexObject',
  full_name='example.third.ComplexObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='example.third.ComplexObject.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='brand', full_name='example.third.ComplexObject.brand', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='childObject', full_name='example.third.ComplexObject.childObject', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=187,
)

_COMPLEXOBJECT.fields_by_name['brand'].enum_type = _BRANDS
_COMPLEXOBJECT.fields_by_name['childObject'].message_type = _CHILDOBJECT
DESCRIPTOR.message_types_by_name['ChildObject'] = _CHILDOBJECT
DESCRIPTOR.message_types_by_name['ComplexObject'] = _COMPLEXOBJECT
DESCRIPTOR.enum_types_by_name['Brands'] = _BRANDS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChildObject = _reflection.GeneratedProtocolMessageType('ChildObject', (_message.Message,), dict(
  DESCRIPTOR = _CHILDOBJECT,
  __module__ = 'complex_pb2'
  # @@protoc_insertion_point(class_scope:example.third.ChildObject)
  ))
_sym_db.RegisterMessage(ChildObject)

ComplexObject = _reflection.GeneratedProtocolMessageType('ComplexObject', (_message.Message,), dict(
  DESCRIPTOR = _COMPLEXOBJECT,
  __module__ = 'complex_pb2'
  # @@protoc_insertion_point(class_scope:example.third.ComplexObject)
  ))
_sym_db.RegisterMessage(ComplexObject)


# @@protoc_insertion_point(module_scope)
